#cloud-config
password: ubuntu
chpasswd:
  expire: False
ssh_pwauth: True

preserve_hostname: false
hostname: runner-${NAME}

growpart:
  mode: auto
  devices: ["/"]
  ignore_growroot_disabled: false
