#cloud-config
password: ubuntu
chpasswd:
  expire: False
ssh_pwauth: True

preserve_hostname: false
hostname: runner-${NAME}
fqdn: runner-${NAME}.ci.konghq.com.internal

growpart:
  mode: auto
  devices: ["/"]
  ignore_growroot_disabled: false
